# Exploração dos Dados

## Visualização Inicial de Alguns Dados

In [27]:
from IPython.display import display
import pandas as pd

data = pd.read_csv('data/raw/active_alarms_prod.csv')
data.head()

,acal_cd_id,acal_cd_alarm_id,acal_tx_node,acal_cd_node_id,acal_tx_node_info,acal_tx_alert_type,acal_nm_severity,acal_nm_occurrences,acal_dt_last_occurrence,acal_dt_first_occurrence,...,acal_tx_node_vendor,acal_tx_node_region,acal_tx_node_supplier,acal_tx_node_site,acal_tx_node_ip_address,acal_tx_description,acal_tx_node_tag,acal_tx_source,acal_tx_ignore_type,acal_js_extra_fields
0,476a7e63-014b-46c0-abaf-e80dc0cacf14,08559a20-f409-4454-9016-1ac36578b4bb,SPCTP-V40HPP-SVT201-01,f3ba8721-2bb0-46b3-b4dd-c9255bb7a3ad,ATLAS,OPENSHIFT_CLUSTER_PVC,2,1,2025-10-06 08:55:11.921937,2025-10-06 08:55:11.921937,...,NaN,NaN,NaN,NaN,NaN,NAMESPACE_PVC is over the limits 1 or 2 or 3 (...,NaN,smartoss,NaN,NaN
1,121548a8-9210-40a7-847f-988781502e3f,104d90ff-0da2-4c93-b7fe-664c17271419,SPCTP-V40HPP-SVT201-01,f3ba8721-2bb0-46b3-b4dd-c9255bb7a3ad,ATLAS,OPENSHIFT_CLUSTER_PVC,1,2,2025-10-06 08:55:11.921937,2025-10-06 08:50:13.193322,...,NaN,NaN,NaN,NaN,NaN,NAMESPACE_PVC is over the limits 1 or 2 or 3 (...,NaN,smartoss,NaN,NaN
2,a801690e-0074-4ad6-835f-9ca8da0c55e8,7b118c2e-f9ed-450b-8a4c-2000c36f7c1c,RJBAR-TAIHUA-ESM31,f02a8eab-0a93-4f87-90f9-3eb96aa9e1aa,HUAWEI-MAE-RJ3,SOFTWARE_SERVICE_STATUS_INFO,2,25,2025-10-27 04:56:51.145393,2025-10-26 05:57:30.12203,...,HUAWEI,RIO DE JANEIRO,HUAWEI,Barra - RJ,10.43.86.21,NEW UNIT FILE (run-r2e9f4aaf23254cfcbf586daccc...,APP,smartoss,NaN,NaN
3,776e0483-ac6f-48d0-921e-373a1cb3b5c7,7dbd3557-e9d5-472a-9fdb-af5af2fecea9,SPCTP-TAIHUA-SVR14,53c8586f-00c4-4f7f-b8b0-ccaa3cf535eb,HUAWEI-U2020-SP1,CAPACITY_DISK_FREE_USED_PERCENT,1,1,2025-10-01 03:10:41.551299,2025-10-01 03:10:41.551299,...,HUAWEI,SAO PAULO,HUAWEI,Tatuapé - SP,187.100.113.9,USED % is over the limits 1 or 2 or 3 (Value =...,APP,smartoss,NaN,NaN
4,e729be90-d67d-4741-a953-50f3603e5c80,2d2818da-4b0a-4d21-8741-7bf027a369ee,spctp-v40hpp-svt231-14,c60cc1af-aa30-491a-a3ef-55c6f8e4d8cd,ATLAS,SPARK_JVM_GARBAGE_COLLECTOR_YOUNG,1,168,2025-10-14 15:20:05.018794,2025-10-14 01:25:05.123944,...,NaN,NaN,NaN,NaN,NaN,JVM_GARBAGE_COLLECTOR_YOUNG is over the limits...,VSMBB,smartoss,NaN,NaN

## Vendo as colunas

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6881 entries, 0 to 6880
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   acal_cd_id                 6881 non-null   object
 1   acal_cd_alarm_id           6881 non-null   object
 2   acal_tx_node               6832 non-null   object
 3   acal_cd_node_id            6881 non-null   object
 4   acal_tx_node_info          6877 non-null   object
 5   acal_tx_alert_type         6881 non-null   object
 6   acal_nm_severity           6881 non-null   int64
 7   acal_nm_occurrences        6881 non-null   int64
 8   acal_dt_last_occurrence    6881 non-null   object
 9   acal_dt_first_occurrence   6881 non-null   object
 10  acal_tx_identifier         6881 non-null   object
 11  acal_nm_probes_alert       6881 non-null   object
 12  acal_tx_snmp_trap          6881 non-null   object
 13  acal_tx_node_distribution  5078 non-null   object
 14  acal_tx_node_vendor        5078 non-null   object
 15  acal_tx_node_region        5078 non-null   object
 16  acal_tx_node_supplier      5078 non-null   object
 17  acal_tx_node_site          5078 non-null   object
 18  acal_tx_node_ip_address    5064 non-null   object
 19  acal_tx_description        6881 non-null   object
 20  acal_tx_node_tag           5486 non-null   object
 21  acal_tx_source             6881 non-null   object
 22  acal_tx_ignore_type        0 non-null      float64
 23  acal_js_extra_fields       5387 non-null   object
dtypes: float64(1), int64(2), object(21)
memory usage: 1.3+ MB

In [30]:
alarm_by_node = data.groupby('acal_tx_node')['acal_cd_alarm_id'].nunique().sort_values(ascending=False)
display(alarm_by_node.to_frame(name='Quantidade de Alarmes'))

                        Quantidade de Alarmes
acal_tx_node
SPCTP-IFOHPP-STR04                       2004
SPCTP-V40HPP-SVT201-01                    538
spctp-v40hpp-svt231-14                    402
UC13-PJ041-BARONEZA                       269
SPCTP-IFOHPP-SWT10                        163
...                                       ...
SPCTP-V02HPP-BLS16                          1
SPCTP-V02HPP-BLS17                          1
SPCTP-V02HPP-BLS18                          1
SPCTP-V02HPP-BLS19                          1
SPCTP-ENMHPP-LMS03                          1

[531 rows x 1 columns]