In [1]:
import polars as pl
from dotenv import load_dotenv
import os

load_dotenv(".env")

from src.repository.alarm_graph_repository import AlarmGraphRepository

lazy_frame = pl.scan_parquet("data/raw/alarm_history_dump.parquet")
graph_repo = AlarmGraphRepository(os.getenv("HISTORY_DB_PATH"))

In [2]:
from src.pipelines.simple_time_correlation import SimpleTimeCorrelationHistory

SimpleTimeCorrelationHistory.train(lazy_frame, graph_repo)

Processando nós: 100%|██████████| 912/912 [05:25<00:00,  2.80nó/s]

In [3]:
from src.postprocess.enumerate_incidents import EnumerateIncidents

EnumerateIncidents.enumerate_data(graph_repo)

graph_repo.preview_nodes()

shape: (20, 6)
┌──────────────────┬──────────┬─────────────────┬─────────────────┬──────────────┬─────────────────┐
│ alert_id         ┆ incident ┆ alert_type      ┆ start_time      ┆ end_time     ┆ node_id         │
│ ---              ┆ ---      ┆ ---             ┆ ---             ┆ ---          ┆ ---             │
│ str              ┆ i32      ┆ str             ┆ datetime[μs]    ┆ datetime[μs] ┆ str             │
╞══════════════════╪══════════╪═════════════════╪═════════════════╪══════════════╪═════════════════╡
│ 65a5d542-bbdf-44 ┆ 155988   ┆ MANAGEMENT_BOAR ┆ 2026-03-12      ┆ null         ┆ 0735063a-6a73-4 │
│ 81-a3a8-7c69a5…  ┆          ┆ D_TEMPERATURE_R ┆ 05:36:12.939274 ┆              ┆ b88-9c87-36c374 │
│                  ┆          ┆ …               ┆                 ┆              ┆ …               │
│ ed999673-98ad-49 ┆ 156470   ┆ MANAGEMENT_BOAR ┆ 2026-03-15      ┆ null         ┆ 0735063a-6a73-4 │
│ 50-b566-c7c4a2…  ┆          ┆ D_TEMPERATURE_R ┆ 16:40:49.653298 ┆              ┆ b88-9c87-36c374 │
│                  ┆          ┆ …               ┆                 ┆              ┆ …               │
│ 66e41ca3-5d34-4d ┆ 157879   ┆ MANAGEMENT_BOAR ┆ 2026-03-26      ┆ null         ┆ 0735063a-6a73-4 │
│ 01-b8b5-e4cea0…  ┆          ┆ D_TEMPERATURE_R ┆ 12:20:56.965146 ┆              ┆ b88-9c87-36c374 │
│                  ┆          ┆ …               ┆                 ┆              ┆ …               │
│ 2c5009fe-e6a9-4c ┆ 158228   ┆ MANAGEMENT_BOAR ┆ 2026-03-28      ┆ null         ┆ 0735063a-6a73-4 │
│ cf-a334-0c94a6…  ┆          ┆ D_TEMPERATURE_R ┆ 22:05:45.376166 ┆              ┆ b88-9c87-36c374 │
│                  ┆          ┆ …               ┆                 ┆              ┆ …               │
│ 6141e7d2-a0a0-4e ┆ 154610   ┆ MANAGEMENT_BOAR ┆ 2026-03-02      ┆ null         ┆ 0735063a-6a73-4 │
│ 5e-941c-64b957…  ┆          ┆ D_TEMPERATURE_R ┆ 11:41:28.805688 ┆              ┆ b88-9c87-36c374 │
│                  ┆          ┆ …               ┆                 ┆              ┆ …               │
│ …                ┆ …        ┆ …               ┆ …               ┆ …            ┆ …               │
│ f5289c2b-fedb-41 ┆ 156575   ┆ MANAGEMENT_BOAR ┆ 2026-03-16      ┆ null         ┆ 0735063a-6a73-4 │
│ 80-b1e2-ec9089…  ┆          ┆ D_TEMPERATURE_R ┆ 11:05:59.971868 ┆              ┆ b88-9c87-36c374 │
│                  ┆          ┆ …               ┆                 ┆              ┆ …               │
│ f2c103f0-03eb-4f ┆ 155525   ┆ MANAGEMENT_BOAR ┆ 2026-03-08      ┆ null         ┆ 0735063a-6a73-4 │
│ c9-bac1-dd763b…  ┆          ┆ D_TEMPERATURE_R ┆ 23:31:10.052212 ┆              ┆ b88-9c87-36c374 │
│                  ┆          ┆ …               ┆                 ┆              ┆ …               │
│ 35f785bc-f6a4-4a ┆ 157977   ┆ MANAGEMENT_BOAR ┆ 2026-03-27      ┆ null         ┆ 0735063a-6a73-4 │
│ 9d-b695-4df567…  ┆          ┆ D_TEMPERATURE_R ┆ 04:30:38.374687 ┆              ┆ b88-9c87-36c374 │
│                  ┆          ┆ …               ┆                 ┆              ┆ …               │
│ a0fe41d0-05e6-42 ┆ 155918   ┆ MANAGEMENT_BOAR ┆ 2026-03-11      ┆ null         ┆ 0735063a-6a73-4 │
│ 8b-ac7f-eedeb0…  ┆          ┆ D_TEMPERATURE_R ┆ 17:31:19.950020 ┆              ┆ b88-9c87-36c374 │
│                  ┆          ┆ …               ┆                 ┆              ┆ …               │
│ f40869d8-417a-40 ┆ 158228   ┆ MANAGEMENT_BOAR ┆ 2026-03-28      ┆ null         ┆ 0735063a-6a73-4 │
│ c5-a64e-d19544…  ┆          ┆ D_TEMPERATURE_R ┆ 22:00:53.028709 ┆              ┆ b88-9c87-36c374 │
│                  ┆          ┆ …               ┆                 ┆              ┆ …               │
└──────────────────┴──────────┴─────────────────┴─────────────────┴──────────────┴─────────────────┘

In [4]:
from src.utils.node_summary import node_summary
from src.repository.aggregate_results_repository import AggregateResultsRepository

summary, general_metrics = node_summary(graph_repo)

results_repo = AggregateResultsRepository(filename="simple_time_corr_history")
results_repo.save(summary)
results_repo.load()

✅ Nova versão salva com sucesso em: data/results/simple_time_corr_history_20260530_140019.csv
📖 Carregando a versão mais recente encontrada: simple_time_corr_history_20260530_140019.csv

shape: (912, 6)
┌───────────────────────┬──────────┬───────────────┬────────────┬──────────────────────┬───────────┐
│ Node ID               ┆ Total de ┆ Total de      ┆ Total de   ┆ Média de Alarmes por ┆ Densidade │
│ ---                   ┆ Alarmes  ┆ Correlações   ┆ Incidentes ┆ Incidente            ┆ ---       │
│ str                   ┆ ---      ┆ ---           ┆ ---        ┆ ---                  ┆ f64       │
│                       ┆ i64      ┆ i64           ┆ i64        ┆ f64                  ┆           │
╞═══════════════════════╪══════════╪═══════════════╪════════════╪══════════════════════╪═══════════╡
│ a5126d4f-0bd1-4023-ae ┆ 232712   ┆ 8584164       ┆ 4090       ┆ 56.8978              ┆ 0.000317  │
│ 9d-d2c1e9…            ┆          ┆               ┆            ┆                      ┆           │
│ 7510d37a-4c5f-40da-b9 ┆ 32148    ┆ 119403        ┆ 4073       ┆ 7.892954             ┆ 0.000231  │
│ 87-3977c2…            ┆          ┆               ┆            ┆                      ┆           │
│ 8bf0d4d2-1cd3-4341-9b ┆ 31766    ┆ 116570        ┆ 4065       ┆ 7.814514             ┆ 0.000231  │
│ 79-794833…            ┆          ┆               ┆            ┆                      ┆           │
│ e4efe34f-1d6d-4fd2-ad ┆ 32023    ┆ 119030        ┆ 4054       ┆ 7.899112             ┆ 0.000232  │
│ 89-6e6b8e…            ┆          ┆               ┆            ┆                      ┆           │
│ 75577cb5-6565-42da-a0 ┆ 27157    ┆ 83723         ┆ 4041       ┆ 6.720366             ┆ 0.000227  │
│ 42-d9603e…            ┆          ┆               ┆            ┆                      ┆           │
│ …                     ┆ …        ┆ …             ┆ …          ┆ …                    ┆ …         │
│ e9488358-73d3-4612-a4 ┆ 714      ┆ 0             ┆ 1          ┆ 714.0                ┆ 0.0       │
│ 13-62ac2b…            ┆          ┆               ┆            ┆                      ┆           │
│ 0b466dd2-3057-4816-93 ┆ 12       ┆ 0             ┆ 1          ┆ 12.0                 ┆ 0.0       │
│ 79-ac1e7e…            ┆          ┆               ┆            ┆                      ┆           │
│ 0ea468f1-9c1d-4386-9e ┆ 711      ┆ 0             ┆ 1          ┆ 711.0                ┆ 0.0       │
│ a8-8ba975…            ┆          ┆               ┆            ┆                      ┆           │
│ a003fd1d-e8e7-4ae7-b1 ┆ 29       ┆ 0             ┆ 1          ┆ 29.0                 ┆ 0.0       │
│ 59-f775f7…            ┆          ┆               ┆            ┆                      ┆           │
│ 338bf29e-d469-40e6-9c ┆ 714      ┆ 0             ┆ 1          ┆ 714.0                ┆ 0.0       │
│ 54-df94f5…            ┆          ┆               ┆            ┆                      ┆           │
└───────────────────────┴──────────┴───────────────┴────────────┴──────────────────────┴───────────┘

In [5]:
graph_repo.close()