In [3]:
import polars as pl
from dotenv import load_dotenv
import os

load_dotenv(".env")

from src.repository.alarm_graph_repository import AlarmGraphRepository

lazy_frame = pl.scan_parquet("data/raw/alarm_history_dump.parquet")
graph_repo = AlarmGraphRepository(os.getenv("HISTORY_DB_PATH"))

In [4]:
from src.pipelines.simple_time_correlation import SimpleTimeCorrelationHistory

SimpleTimeCorrelationHistory.train(lazy_frame, graph_repo)

Processando nós: 100%|██████████| 912/912 [07:22<00:00,  2.06nó/s]

In [5]:
from src.postprocess.enumerate_incidents import EnumerateIncidents

EnumerateIncidents.enumerate_data(graph_repo)

graph_repo.preview_nodes()

Calculando WCC: 100%|██████████| 912/912 [03:57<00:00,  3.85nó/s]

shape: (20, 6)
┌─────────────────────┬────────────────────┬────────────────────┬────────────┬──────────┬──────────┐
│ alert_id            ┆ node_id            ┆ alert_type         ┆ start_time ┆ end_time ┆ incident │
│ ---                 ┆ ---                ┆ ---                ┆ ---        ┆ ---      ┆ ---      │
│ str                 ┆ str                ┆ str                ┆ date       ┆ date     ┆ i32      │
╞═════════════════════╪════════════════════╪════════════════════╪════════════╪══════════╪══════════╡
│ f731a04b-5e80-4fc2- ┆ 50e91219-3c5e-420d ┆ MANAGEMENT_BOARD_T ┆ 2026-03-29 ┆ null     ┆ 3881     │
│ 94b9-49eefd…        ┆ -9c21-0c80cd…      ┆ EMPERATURE_R…      ┆            ┆          ┆          │
│ 9b6cb823-0895-41d5- ┆ 50e91219-3c5e-420d ┆ MANAGEMENT_BOARD_T ┆ 2026-03-07 ┆ null     ┆ 875      │
│ abd0-8ec2ee…        ┆ -9c21-0c80cd…      ┆ EMPERATURE_R…      ┆            ┆          ┆          │
│ 0ea25bc5-ae0f-4b91- ┆ 50e91219-3c5e-420d ┆ MANAGEMENT_BOARD_T ┆ 2026-03-09 ┆ null     ┆ null     │
│ a69a-970925…        ┆ -9c21-0c80cd…      ┆ EMPERATURE_R…      ┆            ┆          ┆          │
│ 83d1c7e9-1a90-4d9b- ┆ 50e91219-3c5e-420d ┆ MANAGEMENT_BOARD_T ┆ 2026-03-08 ┆ null     ┆ 981      │
│ aa87-ba0fc0…        ┆ -9c21-0c80cd…      ┆ EMPERATURE_R…      ┆            ┆          ┆          │
│ d1375fa2-2d33-4753- ┆ 50e91219-3c5e-420d ┆ MANAGEMENT_BOARD_T ┆ 2026-03-28 ┆ null     ┆ 3715     │
│ 891b-79e71e…        ┆ -9c21-0c80cd…      ┆ EMPERATURE_R…      ┆            ┆          ┆          │
│ …                   ┆ …                  ┆ …                  ┆ …          ┆ …        ┆ …        │
│ e3b5cdf9-49fd-4161- ┆ 50e91219-3c5e-420d ┆ MANAGEMENT_BOARD_T ┆ 2026-03-10 ┆ null     ┆ 1282     │
│ 8aaf-5f9a6f…        ┆ -9c21-0c80cd…      ┆ EMPERATURE_R…      ┆            ┆          ┆          │
│ e6b77010-1fa9-458e- ┆ 50e91219-3c5e-420d ┆ MANAGEMENT_BOARD_T ┆ 2026-03-23 ┆ null     ┆ 3054     │
│ 8e73-9ab97d…        ┆ -9c21-0c80cd…      ┆ EMPERATURE_R…      ┆            ┆          ┆          │
│ 93043f74-5865-4b46- ┆ 50e91219-3c5e-420d ┆ MANAGEMENT_BOARD_T ┆ 2026-03-22 ┆ null     ┆ 2813     │
│ 89da-f1b0a0…        ┆ -9c21-0c80cd…      ┆ EMPERATURE_R…      ┆            ┆          ┆          │
│ 188216b1-8d25-4208- ┆ 50e91219-3c5e-420d ┆ MANAGEMENT_BOARD_T ┆ 2026-03-24 ┆ null     ┆ 3076     │
│ ad44-429be9…        ┆ -9c21-0c80cd…      ┆ EMPERATURE_R…      ┆            ┆          ┆          │
│ 4713037b-2c27-4fb9- ┆ 50e91219-3c5e-420d ┆ MANAGEMENT_BOARD_T ┆ 2026-03-28 ┆ null     ┆ 3707     │
│ 90d7-11312d…        ┆ -9c21-0c80cd…      ┆ EMPERATURE_R…      ┆            ┆          ┆          │
└─────────────────────┴────────────────────┴────────────────────┴────────────┴──────────┴──────────┘

In [6]:
from src.utils.node_summary import node_summary
from src.repository.aggregate_results_repository import AggregateResultsRepository

summary, general_metrics = node_summary(graph_repo)

results_repo = AggregateResultsRepository(filename="simple_time_corr_history")
results_repo.save(summary)
results_repo.load()

✅ Nova versão salva com sucesso em: data/results/simple_time_corr_history_20260520_170147.csv
📖 Carregando a versão mais recente encontrada: simple_time_corr_history_20260520_170147.csv

shape: (912, 6)
┌───────────────────────┬──────────┬───────────────┬────────────┬──────────────────────┬───────────┐
│ Node ID               ┆ Total de ┆ Total de      ┆ Total de   ┆ Média de Alarmes por ┆ Densidade │
│ ---                   ┆ Alarmes  ┆ Correlações   ┆ Incidentes ┆ Incidente            ┆ ---       │
│ str                   ┆ ---      ┆ ---           ┆ ---        ┆ ---                  ┆ f64       │
│                       ┆ i64      ┆ i64           ┆ i64        ┆ f64                  ┆           │
╞═══════════════════════╪══════════╪═══════════════╪════════════╪══════════════════════╪═══════════╡
│ a5126d4f-0bd1-4023-ae ┆ 232712   ┆ 8584164       ┆ 4090       ┆ 56.8978              ┆ 0.000317  │
│ 9d-d2c1e9…            ┆          ┆               ┆            ┆                      ┆           │
│ 7510d37a-4c5f-40da-b9 ┆ 32148    ┆ 119403        ┆ 4073       ┆ 7.892954             ┆ 0.000231  │
│ 87-3977c2…            ┆          ┆               ┆            ┆                      ┆           │
│ 8bf0d4d2-1cd3-4341-9b ┆ 31766    ┆ 116570        ┆ 4065       ┆ 7.814514             ┆ 0.000231  │
│ 79-794833…            ┆          ┆               ┆            ┆                      ┆           │
│ e4efe34f-1d6d-4fd2-ad ┆ 32023    ┆ 119030        ┆ 4054       ┆ 7.899112             ┆ 0.000232  │
│ 89-6e6b8e…            ┆          ┆               ┆            ┆                      ┆           │
│ 75577cb5-6565-42da-a0 ┆ 27157    ┆ 83723         ┆ 4041       ┆ 6.720366             ┆ 0.000227  │
│ 42-d9603e…            ┆          ┆               ┆            ┆                      ┆           │
│ …                     ┆ …        ┆ …             ┆ …          ┆ …                    ┆ …         │
│ 2ccfd5c5-2244-4e8e-98 ┆ 242      ┆ 0             ┆ 1          ┆ 242.0                ┆ 0.0       │
│ 0e-7ad5e2…            ┆          ┆               ┆            ┆                      ┆           │
│ 70698859-ea2b-41be-a0 ┆ 11       ┆ 0             ┆ 1          ┆ 11.0                 ┆ 0.0       │
│ d8-d29f4c…            ┆          ┆               ┆            ┆                      ┆           │
│ 44837bb2-30ba-4375-93 ┆ 755      ┆ 0             ┆ 1          ┆ 755.0                ┆ 0.0       │
│ 03-497045…            ┆          ┆               ┆            ┆                      ┆           │
│ 99a6b09f-9065-4f43-ad ┆ 711      ┆ 0             ┆ 1          ┆ 711.0                ┆ 0.0       │
│ d9-542a89…            ┆          ┆               ┆            ┆                      ┆           │
│ bed7f5e2-55a9-4d53-84 ┆ 43       ┆ 0             ┆ 1          ┆ 43.0                 ┆ 0.0       │
│ 96-6d5540…            ┆          ┆               ┆            ┆                      ┆           │
└───────────────────────┴──────────┴───────────────┴────────────┴──────────────────────┴───────────┘