In [ ]:
from src.preprocess.parquet_preprocessor import ParquetPreprocessor

ParquetPreprocessor.csv_to_parquet("data/raw/active_alarms_prod.csv", "data/raw/active_alarms_prod.parquet")

In [1]:
import polars as pl
from dotenv import load_dotenv
import os

load_dotenv(".env")

from src.repository.alarm_graph_repository import AlarmGraphRepository

lazy_frame = pl.scan_parquet("data/raw/active_alarms_prod.parquet")
graph_repo = AlarmGraphRepository(os.getenv("ACTIVE_DB_PATH"))

In [2]:
from src.pipelines.simple_time_correlation import SimpleTimeCorrelationActive

SimpleTimeCorrelationActive.train(lazy_frame, graph_repo)

Processando nós: 100%|██████████| 866/866 [00:13<00:00, 63.69nó/s]

In [4]:
from src.postprocess.enumerate_incidents import EnumerateIncidents

EnumerateIncidents.enumerate_data(graph_repo)

graph_repo.preview_nodes()

Calculando WCC: 100%|██████████| 866/866 [00:03<00:00, 288.51nó/s]

shape: (20, 6)
┌────────────────────┬────────────────────┬───────────────────┬────────────┬────────────┬──────────┐
│ alert_id           ┆ node_id            ┆ alert_type        ┆ start_time ┆ end_time   ┆ incident │
│ ---                ┆ ---                ┆ ---               ┆ ---        ┆ ---        ┆ ---      │
│ str                ┆ str                ┆ str               ┆ date       ┆ date       ┆ i32      │
╞════════════════════╪════════════════════╪═══════════════════╪════════════╪════════════╪══════════╡
│ 305da354-2edf-444e ┆ 11dabbf8-b36c-42e6 ┆ STORAGE_VOLUME_ST ┆ 2025-12-05 ┆ 2025-12-05 ┆ 0        │
│ -a2b7-4edb06…      ┆ -9695-51ac6c…      ┆ ATUS_IOSZ_QLE…    ┆            ┆            ┆          │
│ 8a6acea4-c8db-46f8 ┆ 11dabbf8-b36c-42e6 ┆ STORAGE_VOLUME_ST ┆ 2025-12-05 ┆ 2025-12-05 ┆ 0        │
│ -8c6a-0ca91a…      ┆ -9695-51ac6c…      ┆ ATUS_IOSZ_CUR     ┆            ┆            ┆          │
│ 514ed2e4-e107-4d2b ┆ 11dabbf8-b36c-42e6 ┆ STORAGE_VOLUME_ST ┆ 2025-12-05 ┆ 2025-12-05 ┆ 0        │
│ -82ba-a232c6…      ┆ -9695-51ac6c…      ┆ ATUS_IOSZ_AVG     ┆            ┆            ┆          │
│ 4ef9274c-e078-468f ┆ 11dabbf8-b36c-42e6 ┆ STORAGE_PHYSICAL_ ┆ 2025-11-11 ┆ 2025-12-05 ┆ 0        │
│ -8b3f-dc44d3…      ┆ -9695-51ac6c…      ┆ DISK_ALLOCATI…    ┆            ┆            ┆          │
│ 88b82f4c-e0a0-4097 ┆ 11dabbf8-b36c-42e6 ┆ STORAGE_VOLUME_ST ┆ 2025-12-05 ┆ 2025-12-05 ┆ 0        │
│ -844a-84d5b3…      ┆ -9695-51ac6c…      ┆ ATUS_IOSZ_AVG     ┆            ┆            ┆          │
│ …                  ┆ …                  ┆ …                 ┆ …          ┆ …          ┆ …        │
│ a9518d63-8bd3-40eb ┆ 11dabbf8-b36c-42e6 ┆ STORAGE_VOLUME_ST ┆ 2025-12-05 ┆ 2025-12-05 ┆ 0        │
│ -ab46-710461…      ┆ -9695-51ac6c…      ┆ ATUS_KBYTES_P…    ┆            ┆            ┆          │
│ d046d918-6938-4705 ┆ 11dabbf8-b36c-42e6 ┆ STORAGE_VOLUME_ST ┆ 2025-12-05 ┆ 2025-12-05 ┆ 0        │
│ -9caf-672fbd…      ┆ -9695-51ac6c…      ┆ ATUS_IO_PER_S…    ┆            ┆            ┆          │
│ 08d790f7-1153-456b ┆ 11dabbf8-b36c-42e6 ┆ STORAGE_VOLUME_ST ┆ 2025-12-05 ┆ 2025-12-05 ┆ 0        │
│ -983f-80d267…      ┆ -9695-51ac6c…      ┆ ATUS_KBYTES_P…    ┆            ┆            ┆          │
│ fdaf1cf1-f207-4f53 ┆ 11dabbf8-b36c-42e6 ┆ STORAGE_VOLUME_ST ┆ 2025-12-05 ┆ 2025-12-05 ┆ 0        │
│ -9af7-0d2e5a…      ┆ -9695-51ac6c…      ┆ ATUS_SVT_CUR      ┆            ┆            ┆          │
│ a9f8ed34-065a-4ae9 ┆ 11dabbf8-b36c-42e6 ┆ STORAGE_VOLUME_ST ┆ 2025-12-05 ┆ 2025-12-05 ┆ 0        │
│ -91ab-a48f95…      ┆ -9695-51ac6c…      ┆ ATUS_IO_PER_S…    ┆            ┆            ┆          │
└────────────────────┴────────────────────┴───────────────────┴────────────┴────────────┴──────────┘

In [2]:
from src.utils.node_summary import node_summary
from src.repository.aggregate_results_repository import AggregateResultsRepository

summary, general_metrics = node_summary(graph_repo)

results_repo = AggregateResultsRepository(filename="simple_time_corr_active")
results_repo.save(summary)
results_repo.load()

✅ Nova versão salva com sucesso em: data/results/simple_time_corr_active_20260519_180956.csv
📖 Carregando a versão mais recente encontrada: simple_time_corr_active_20260519_180956.csv

shape: (866, 6)
┌───────────────────────┬──────────┬───────────────┬────────────┬──────────────────────┬───────────┐
│ Node ID               ┆ Total de ┆ Total de      ┆ Total de   ┆ Média de Alarmes por ┆ Densidade │
│ ---                   ┆ Alarmes  ┆ Correlações   ┆ Incidentes ┆ Incidente            ┆ ---       │
│ str                   ┆ ---      ┆ ---           ┆ ---        ┆ ---                  ┆ f64       │
│                       ┆ i64      ┆ i64           ┆ i64        ┆ f64                  ┆           │
╞═══════════════════════╪══════════╪═══════════════╪════════════╪══════════════════════╪═══════════╡
│ c60cc1af-aa30-491a-a3 ┆ 399      ┆ 417           ┆ 130        ┆ 3.069231             ┆ 0.005252  │
│ ef-55c6f8…            ┆          ┆               ┆            ┆                      ┆           │
│ f3ba8721-2bb0-46b3-b4 ┆ 237      ┆ 12358         ┆ 18         ┆ 13.166667            ┆ 0.441894  │
│ dd-c9255b…            ┆          ┆               ┆            ┆                      ┆           │
│ 4a278aa6-9cfe-4d85-ae ┆ 60       ┆ 4             ┆ 4          ┆ 15.0                 ┆ 0.00226   │
│ 05-9843e5…            ┆          ┆               ┆            ┆                      ┆           │
│ 4c43b243-0774-4296-8f ┆ 57       ┆ 4             ┆ 4          ┆ 14.25                ┆ 0.002506  │
│ 18-85c699…            ┆          ┆               ┆            ┆                      ┆           │
│ 3a15506c-b858-4cd5-8b ┆ 60       ┆ 4             ┆ 4          ┆ 15.0                 ┆ 0.00226   │
│ ba-8fafdc…            ┆          ┆               ┆            ┆                      ┆           │
│ …                     ┆ …        ┆ …             ┆ …          ┆ …                    ┆ …         │
│ 068f4329-2d28-4e6f-b4 ┆ 1        ┆ 0             ┆ 1          ┆ 1.0                  ┆ 0.0       │
│ bf-7249f4…            ┆          ┆               ┆            ┆                      ┆           │
│ 76570354-6bff-4143-91 ┆ 1        ┆ 0             ┆ 1          ┆ 1.0                  ┆ 0.0       │
│ e0-7e6c9b…            ┆          ┆               ┆            ┆                      ┆           │
│ c9a3f847-3474-4352-bd ┆ 1        ┆ 0             ┆ 1          ┆ 1.0                  ┆ 0.0       │
│ 42-c6fbe7…            ┆          ┆               ┆            ┆                      ┆           │
│ 5f8521b7-d6cd-4446-9a ┆ 1        ┆ 0             ┆ 1          ┆ 1.0                  ┆ 0.0       │
│ 80-80fcaa…            ┆          ┆               ┆            ┆                      ┆           │
│ fffe18aa-5cb5-4507-8e ┆ 1        ┆ 0             ┆ 1          ┆ 1.0                  ┆ 0.0       │
│ 72-1ee0c5…            ┆          ┆               ┆            ┆                      ┆           │
└───────────────────────┴──────────┴───────────────┴────────────┴──────────────────────┴───────────┘