In [ ]:
from src.preprocess.parquet_preprocessor import ParquetPreprocessor

ParquetPreprocessor.csv_to_parquet("data/raw/active_alarms_prod.csv", "data/raw/active_alarms_prod.parquet")

In [1]:
import polars as pl
from dotenv import load_dotenv
import os

load_dotenv(".env")

from src.repository.alarm_graph_repository import AlarmGraphRepository

lazy_frame = pl.scan_parquet("data/raw/active_alarms_prod.parquet")
graph_repo = AlarmGraphRepository(os.getenv("ACTIVE_DB_PATH"))

In [2]:
from src.pipelines.simple_time_correlation import SimpleTimeCorrelationActive

SimpleTimeCorrelationActive.train(lazy_frame, graph_repo)

In [3]:
from src.postprocess.enumerate_incidents import EnumerateIncidents

EnumerateIncidents.enumerate_data(graph_repo)

graph_repo.preview_nodes()

shape: (20, 6)
┌─────────────────┬──────────┬─────────────────┬─────────────────┬────────────────┬────────────────┐
│ alert_id        ┆ incident ┆ alert_type      ┆ start_time      ┆ end_time       ┆ node_id        │
│ ---             ┆ ---      ┆ ---             ┆ ---             ┆ ---            ┆ ---            │
│ str             ┆ i32      ┆ str             ┆ datetime[μs]    ┆ datetime[μs]   ┆ str            │
╞═════════════════╪══════════╪═════════════════╪═════════════════╪════════════════╪════════════════╡
│ 227d1b9c-fce4-4 ┆ 0        ┆ CONNECTIVITY_PO ┆ 2025-11-08      ┆ 2025-12-05 18: ┆ 4c98ad29-ce57- │
│ f15-a1c2-cc530c ┆          ┆ RT_STATE_INFO   ┆ 21:20:17.162669 ┆ 25:14.397934   ┆ 42a7-9fdb-f46d │
│ …               ┆          ┆                 ┆                 ┆                ┆ 87…            │
│ bc5fbc90-51c6-4 ┆ 0        ┆ CONNECTIVITY_PO ┆ 2025-08-22      ┆ 2025-12-05 17: ┆ 4c98ad29-ce57- │
│ e5e-9ecb-0264d1 ┆          ┆ RT_STATE_SFP_AM ┆ 18:41:09.054549 ┆ 42:12.543613   ┆ 42a7-9fdb-f46d │
│ …               ┆          ┆ …               ┆                 ┆                ┆ 87…            │
│ 2201ee65-d32a-4 ┆ 0        ┆ CONNECTIVITY_PO ┆ 2025-11-08      ┆ 2025-12-05 18: ┆ 4c98ad29-ce57- │
│ 1d9-af75-b2d653 ┆          ┆ RT_STATE_INFO   ┆ 21:20:17.162669 ┆ 25:14.397934   ┆ 42a7-9fdb-f46d │
│ …               ┆          ┆                 ┆                 ┆                ┆ 87…            │
│ fdfb2827-2ed4-4 ┆ 0        ┆ CONNECTIVITY_PO ┆ 2025-08-22      ┆ 2025-12-05 17: ┆ 4c98ad29-ce57- │
│ 87b-a59c-9439c3 ┆          ┆ RT_STATE_SFP_AM ┆ 18:41:09.054549 ┆ 42:12.543613   ┆ 42a7-9fdb-f46d │
│ …               ┆          ┆ …               ┆                 ┆                ┆ 87…            │
│ 59787d84-d058-4 ┆ 0        ┆ HARDWARE_INTEGR ┆ 2025-08-22      ┆ 2025-12-05 18: ┆ 4c98ad29-ce57- │
│ 1a0-9c50-b8fa33 ┆          ┆ ITY_FAN_STATUS_ ┆ 19:00:29.219868 ┆ 00:19.282548   ┆ 42a7-9fdb-f46d │
│ …               ┆          ┆ …               ┆                 ┆                ┆ 87…            │
│ …               ┆ …        ┆ …               ┆ …               ┆ …              ┆ …              │
│ 979f496f-5d6e-4 ┆ 0        ┆ CONNECTIVITY_PO ┆ 2025-11-08      ┆ 2025-12-05 18: ┆ 4c98ad29-ce57- │
│ 80d-b9bf-c9d92a ┆          ┆ RT_STATE_INFO   ┆ 21:20:17.162669 ┆ 25:14.397934   ┆ 42a7-9fdb-f46d │
│ …               ┆          ┆                 ┆                 ┆                ┆ 87…            │
│ d2fe184b-270d-4 ┆ 0        ┆ CONNECTIVITY_PO ┆ 2025-08-22      ┆ 2025-12-05 17: ┆ 4c98ad29-ce57- │
│ 3b4-baa9-7016fc ┆          ┆ RT_STATE_SFP_AM ┆ 18:41:09.054549 ┆ 42:12.543613   ┆ 42a7-9fdb-f46d │
│ …               ┆          ┆ …               ┆                 ┆                ┆ 87…            │
│ 25ba2b1a-e8e5-4 ┆ 0        ┆ CONNECTIVITY_PO ┆ 2025-11-08      ┆ 2025-12-05 18: ┆ 4c98ad29-ce57- │
│ be7-bba1-cb9898 ┆          ┆ RT_STATE_INFO   ┆ 21:20:17.162669 ┆ 25:14.397934   ┆ 42a7-9fdb-f46d │
│ …               ┆          ┆                 ┆                 ┆                ┆ 87…            │
│ e98164b6-797a-4 ┆ 0        ┆ CONNECTIVITY_PO ┆ 2025-08-22      ┆ 2025-12-05 17: ┆ 4c98ad29-ce57- │
│ 65b-b045-169e18 ┆          ┆ RT_STATE_SFP_AM ┆ 18:41:09.054549 ┆ 42:12.543613   ┆ 42a7-9fdb-f46d │
│ …               ┆          ┆ …               ┆                 ┆                ┆ 87…            │
│ 8cdb89da-33cf-4 ┆ 0        ┆ CONNECTIVITY_PO ┆ 2025-11-08      ┆ 2025-12-05 18: ┆ 4c98ad29-ce57- │
│ 03b-a5b1-d97eba ┆          ┆ RT_STATE_INFO   ┆ 21:20:17.162669 ┆ 25:14.397934   ┆ 42a7-9fdb-f46d │
│ …               ┆          ┆                 ┆                 ┆                ┆ 87…            │
└─────────────────┴──────────┴─────────────────┴─────────────────┴────────────────┴────────────────┘

In [4]:
from src.utils.node_summary import node_summary
from src.repository.aggregate_results_repository import AggregateResultsRepository

summary, general_metrics = node_summary(graph_repo)

results_repo = AggregateResultsRepository(filename="simple_time_corr_active")
results_repo.save(summary)
results_repo.load()

✅ Nova versão salva com sucesso em: data/results/simple_time_corr_active_20260528_204146.csv
📖 Carregando a versão mais recente encontrada: simple_time_corr_active_20260528_204146.csv

shape: (866, 6)
┌───────────────────────┬──────────┬───────────────┬────────────┬──────────────────────┬───────────┐
│ Node ID               ┆ Total de ┆ Total de      ┆ Total de   ┆ Média de Alarmes por ┆ Densidade │
│ ---                   ┆ Alarmes  ┆ Correlações   ┆ Incidentes ┆ Incidente            ┆ ---       │
│ str                   ┆ ---      ┆ ---           ┆ ---        ┆ ---                  ┆ f64       │
│                       ┆ i64      ┆ i64           ┆ i64        ┆ f64                  ┆           │
╞═══════════════════════╪══════════╪═══════════════╪════════════╪══════════════════════╪═══════════╡
│ c60cc1af-aa30-491a-a3 ┆ 399      ┆ 417           ┆ 130        ┆ 3.069231             ┆ 0.005252  │
│ ef-55c6f8…            ┆          ┆               ┆            ┆                      ┆           │
│ f3ba8721-2bb0-46b3-b4 ┆ 237      ┆ 12358         ┆ 18         ┆ 13.166667            ┆ 0.441894  │
│ dd-c9255b…            ┆          ┆               ┆            ┆                      ┆           │
│ 4c43b243-0774-4296-8f ┆ 57       ┆ 4             ┆ 4          ┆ 14.25                ┆ 0.002506  │
│ 18-85c699…            ┆          ┆               ┆            ┆                      ┆           │
│ 4a278aa6-9cfe-4d85-ae ┆ 60       ┆ 4             ┆ 4          ┆ 15.0                 ┆ 0.00226   │
│ 05-9843e5…            ┆          ┆               ┆            ┆                      ┆           │
│ f02a8eab-0a93-4f87-90 ┆ 60       ┆ 4             ┆ 4          ┆ 15.0                 ┆ 0.00226   │
│ f9-3eb96a…            ┆          ┆               ┆            ┆                      ┆           │
│ …                     ┆ …        ┆ …             ┆ …          ┆ …                    ┆ …         │
│ d17942ed-da6b-4379-86 ┆ 1        ┆ 0             ┆ 1          ┆ 1.0                  ┆ 0.0       │
│ cd-c23908…            ┆          ┆               ┆            ┆                      ┆           │
│ 770bd060-95c8-45a3-85 ┆ 1        ┆ 0             ┆ 1          ┆ 1.0                  ┆ 0.0       │
│ c5-6134dd…            ┆          ┆               ┆            ┆                      ┆           │
│ e3e55b67-76d8-4e6c-89 ┆ 1        ┆ 0             ┆ 1          ┆ 1.0                  ┆ 0.0       │
│ 28-265981…            ┆          ┆               ┆            ┆                      ┆           │
│ ecedff4d-a507-4fac-b0 ┆ 1        ┆ 0             ┆ 1          ┆ 1.0                  ┆ 0.0       │
│ 79-c6b342…            ┆          ┆               ┆            ┆                      ┆           │
│ ea4bb0a1-cedf-4621-ae ┆ 1        ┆ 0             ┆ 1          ┆ 1.0                  ┆ 0.0       │
│ ee-fccb48…            ┆          ┆               ┆            ┆                      ┆           │
└───────────────────────┴──────────┴───────────────┴────────────┴──────────────────────┴───────────┘

In [5]:
graph_repo.close()